"use client";

import { useState } from "react";
import { BookOpen, Bot, Check, ChevronRight, CircleHelp, Clock3, FileText, Image as ImageIcon, KeyRound, LayoutDashboard, Link2, Menu, MoreHorizontal, PenLine, Play, Plus, RefreshCw, Rocket, Search, Send, Settings2, Sparkles, Wand2, X, Youtube, Zap } from "lucide-react";

type NavKey = "overview" | "write" | "assets" | "publish" | "settings";
const styles = [
  ["默认风格", "2000–4000 字", "适合大多数主题"], ["高流量 / 爆款", "2500–4000 字", "强钩子、节奏快"], ["清单体 / 方法论", "2000–4000 字", "结构清晰、可执行"], ["资源盘点", "3000–6000 字", "适合工具与合集"], ["个人实测推荐", "4000–7000 字", "真实体验、带观点"], ["故事化 / 情感共鸣", "2500–4500 字", "更有温度"],
];
const steps = ["构思", "写作", "去痕", "配图", "发布"];

export default function Home() {
  const [nav, setNav] = useState<NavKey>("overview");
  const [topic, setTopic] = useState("AI 时代，普通人如何建立自己的内容工作流？");
  const [style, setStyle] = useState("高流量 / 爆款");
  const [searchOn, setSearchOn] = useState(true);
  const [running, setRunning] = useState(false);
  const [generated, setGenerated] = useState(false);
  const [humanized, setHumanized] = useState(false);
  const [images, setImages] = useState(false);
  const [article, setArticle] = useState<any>(null);
  const [toast, setToast] = useState("");
  const notify = (message: string) => { setToast(message); setTimeout(() => setToast(""), 2400); };
  const start = async () => { setRunning(true); setHumanized(false); setImages(false); try { const response = await fetch("/api/generate", { method: "POST", headers: { "Content-Type": "application/json" }, body: JSON.stringify({ topic, style, search: searchOn }) }); const data = await response.json(); if (!response.ok) throw new Error(data.error || "生成失败"); setArticle(data); setGenerated(true); notify(data.demo ? "已生成演示初稿（配置模型后可生成真实内容）" : "文章初稿已生成"); } catch (error: any) { notify(error.message || "生成失败，请稍后重试"); } finally { setRunning(false); } };
  const navItems: [NavKey, React.ReactNode, string][] = [["overview", <LayoutDashboard size={18}/>, "工作台"], ["write", <PenLine size={18}/>, "写文章"], ["assets", <ImageIcon size={18}/>, "素材库"], ["publish", <Send size={18}/>, "发布中心"], ["settings", <Settings2 size={18}/>, "配置中心"]];

  return <main className="shell">
    <aside className="sidebar">
      <div className="brand"><div className="brand-mark"><Sparkles size={17}/></div><span>墨稿</span><small>AI CONTENT STUDIO</small></div>
      <div className="workspace"><div className="avatar">A</div><div><b>开发阿雷</b><small>个人工作空间</small></div><ChevronRight size={15}/></div>
      <nav>{navItems.map(([key, icon, label]) => <button key={key} className={nav === key ? "nav-item active" : "nav-item"} onClick={() => setNav(key)}>{icon}<span>{label}</span>{key === "publish" && <i>2</i>}</button>)}</nav>
      <div className="side-bottom"><div className="usage"><div className="usage-head"><span>本月使用量</span><b>68%</b></div><div className="progress"><span /></div><small>还剩 32% · 重置于 12 天后</small></div><button className="help"><CircleHelp size={17}/> 使用帮助 <span>?</span></button><div className="user-row"><div className="avatar soft">阿</div><div><b>开发阿雷</b><small>Pro 计划</small></div><MoreHorizontal size={17}/></div></div>
    </aside>
    <section className="content">
      <header className="topbar"><div className="crumb"><button className="mobile-menu"><Menu size={20}/></button><span>{nav === "settings" ? "配置中心" : nav === "write" ? "写文章" : "工作台"}</span><ChevronRight size={14}/><b>{nav === "overview" ? "概览" : nav === "write" ? "新建文章" : nav === "settings" ? "AI 与平台配置" : "全部内容"}</b></div><div className="top-actions"><button className="icon-btn"><Search size={18}/></button><button className="new-btn" onClick={() => { setNav("write"); window.scrollTo({ top: 0, behavior: "smooth" }); }}><Plus size={17}/> 新建文章</button></div></header>
      {nav === "settings" ? <SettingsPage notify={notify}/> : nav === "write" ? <WritePage topic={topic} setTopic={setTopic} style={style} setStyle={setStyle} searchOn={searchOn} setSearchOn={setSearchOn} running={running} start={start} generated={generated} humanized={humanized} setHumanized={setHumanized} images={images} setImages={setImages} article={article} setArticle={setArticle} notify={notify}/> : nav === "assets" ? <AssetsPage notify={notify}/> : nav === "publish" ? <PublishPage notify={notify}/> : <Dashboard onWrite={() => setNav("write")} notify={notify}/>} 
    </section>
    {toast && <div className="toast"><Check size={16}/> {toast}</div>}
  </main>;
}

function Dashboard({ onWrite, notify }: { onWrite: () => void; notify: (s: string) => void }) {
  return <div className="page"><div className="hero"><div><p className="eyebrow"><span className="live-dot"/> 星期一，9 月 14 日</p><h1>早上好，开发阿雷 <span>👋</span></h1><p className="hero-sub">今天也来写点让人愿意读下去的内容吧。</p></div><button className="primary-btn" onClick={onWrite}><PenLine size={17}/> 开始写作 <ChevronRight size={16}/></button></div>
    <div className="stats"><Stat icon={<FileText/>} color="purple" label="本月文章" value="12" delta="+3"/><Stat icon={<Send/>} color="blue" label="已发布" value="8" delta="+2"/><Stat icon={<Zap/>} color="orange" label="节省时间" value="24.5h" delta="+18%"/><Stat icon={<Clock3/>} color="green" label="平均生成" value="3m 42s" delta="-12%"/></div>
    <div className="section-title"><div><h2>最近创作</h2><p>继续你的创作，灵感不会等待。</p></div><button className="text-btn">查看全部 <ChevronRight size={15}/></button></div>
    <div className="recent-grid"><ArticleCard title="AI 时代，普通人如何建立自己的内容工作流？" tag="高流量 / 爆款" status="编辑中" time="刚刚" color="lavender" onClick={onWrite}/><ArticleCard title="我用 7 天时间，重新设计了我的信息输入系统" tag="个人实测推荐" status="已发布" time="昨天" color="peach"/><ArticleCard title="别再盲目囤工具：2024 年真正值得收藏的 12 个 AI 应用" tag="资源盘点" status="草稿" time="3 天前" color="mint"/></div>
    <div className="lower"><div className="section-title"><div><h2>创作流程</h2><p>从灵感到发布，一站式完成。</p></div></div><div className="flow-card">{steps.map((s, i) => <div className="flow-step" key={s}><div className={i < 2 ? "flow-icon done" : "flow-icon"}>{i < 2 ? <Check size={16}/> : i === 2 ? <Wand2 size={17}/> : i === 3 ? <ImageIcon size={17}/> : <Rocket size={17}/>}</div><b>{s}</b>{i < steps.length - 1 && <div className={i < 1 ? "flow-line done" : "flow-line"}/>}</div>)}</div></div>
  </div>;
}
function Stat({ icon, color, label, value, delta }: {icon: React.ReactNode;color:string;label:string;value:string;delta:string}) { return <div className="stat-card"><div className={`stat-icon ${color}`}>{icon}</div><div><small>{label}</small><strong>{value}</strong><span className={delta.startsWith("-") ? "down" : "up"}>{delta}</span></div></div>; }
function ArticleCard({ title, tag, status, time, color, onClick }: {title:string;tag:string;status:string;time:string;color:string;onClick?:()=>void}) { return <button className="article-card" onClick={onClick}><div className={`article-cover ${color}`}><div className="cover-orb"/><span>{tag}</span></div><div className="article-meta"><span className="status"><i className={status === "已发布" ? "green-dot" : "yellow-dot"}/>{status}</span><small>{time}</small></div><h3>{title}</h3><div className="card-footer"><span><FileText size={14}/> 2,846 字</span><span><ImageIcon size={14}/> 3 张配图</span><MoreHorizontal size={16}/></div></button>; }

function AssetsPage({ notify }: { notify: (s: string) => void }) {
  const assets = [{ name: "workflow-cover.png", type: "封面图", size: "1.2 MB", color: "lavender" }, { name: "input-system.png", type: "段落配图", size: "860 KB", color: "peach" }, { name: "ai-tools-roundup.png", type: "封面图", size: "1.5 MB", color: "mint" }, { name: "attention-map.png", type: "段落配图", size: "920 KB", color: "blue" }];
  return <div className="page"><div className="page-heading"><div><p className="eyebrow">内容资产</p><h1>素材库</h1><p className="hero-sub">统一管理文章封面、段落插图和上传素材。</p></div><button className="primary-btn" onClick={() => notify("请选择本地图片上传") }><Plus size={17}/> 上传素材</button></div><div className="asset-toolbar"><div className="asset-tabs"><button className="active">全部 <b>24</b></button><button>封面图 <b>9</b></button><button>段落配图 <b>15</b></button></div><button className="filter-btn"><Search size={15}/> 搜索素材</button></div><div className="asset-grid">{assets.map((asset) => <div className="asset-card" key={asset.name}><div className={`asset-thumb ${asset.color}`}><div className="cover-orb"/><ImageIcon size={20}/></div><div className="asset-info"><b>{asset.name}</b><small>{asset.type} · {asset.size}</small></div><button className="asset-use" onClick={() => notify(`已复制 ${asset.name} 的使用路径`)}><Link2 size={14}/> 使用</button></div>)}</div></div>;
}

function PublishPage({ notify }: { notify: (s: string) => void }) {
  const [selected, setSelected] = useState("wechat");
  const channels = [["wechat", "微信公众号", <BookOpen size={18}/>, "已配置"], ["xiaohongshu", "小红书", <PenLine size={18}/>, "未配置"], ["zhihu", "知乎", <FileText size={18}/>, "未配置"]] as const;
  return <div className="page"><div className="page-heading"><div><p className="eyebrow">内容分发</p><h1>发布中心</h1><p className="hero-sub">选择平台，管理草稿和发布状态。</p></div><button className="primary-btn" onClick={() => notify("请先在写作页生成文章") }><Send size={17}/> 新建发布</button></div><div className="publish-stats"><div><small>待处理</small><strong>2</strong></div><div><small>本月已发布</small><strong>8</strong></div><div><small>成功率</small><strong>100%</strong></div></div><div className="publish-layout"><div className="channel-panel panel"><h2>发布渠道</h2><p>选择一个平台查看队列。</p>{channels.map(([id, name, icon, status]) => <button className={selected === id ? "channel-row active" : "channel-row"} onClick={() => setSelected(id)} key={id}>{icon}<span><b>{name}</b><small>{status}</small></span><ChevronRight size={15}/></button>)}</div><div className="panel queue-panel"><div className="panel-title"><div><h2>待发布队列</h2><p>共 2 篇内容等待处理</p></div><button className="filter-btn"><Clock3 size={14}/> 最近更新</button></div><div className="queue-item"><div className="queue-cover lavender"><div className="cover-orb"/></div><div className="queue-info"><span className="pill warning">草稿</span><b>AI 时代，普通人如何建立自己的内容工作流？</b><small>高流量 / 爆款 · 3,128 字 · 5 个章节</small></div><button className="queue-action" onClick={() => notify("已打开文章编辑")}>编辑</button></div><div className="queue-item"><div className="queue-cover peach"><div className="cover-orb"/></div><div className="queue-info"><span className="pill pending">等待发布</span><b>我用 7 天时间，重新设计了我的信息输入系统</b><small>个人实测推荐 · 昨天创建</small></div><button className="queue-action" onClick={() => notify("已取消发布任务")}>暂停</button></div><button className="wide-outline" onClick={() => notify(`${selected === "wechat" ? "微信公众号" : "当前渠道"}发布队列已刷新`)}><RefreshCw size={15}/> 刷新发布状态</button></div></div></div>;
}

function WritePage({ topic, setTopic, style, setStyle, searchOn, setSearchOn, running, start, generated, humanized, setHumanized, images, setImages, article, setArticle, notify }: any) {
  const [working, setWorking] = useState(false);
  const [previewTab, setPreviewTab] = useState("article");
  const handleHumanize = async () => { if (!article?.content) return; setWorking(true); try { const response = await fetch("/api/humanize", { method: "POST", headers: { "Content-Type": "application/json" }, body: JSON.stringify({ content: article.content }) }); const data = await response.json(); setArticle({ ...article, humanizedContent: data.content }); setHumanized(true); notify(data.demo ? "已完成演示去痕（配置模型后效果更完整）" : "去痕处理完成"); } catch { notify("去痕失败，请稍后重试"); } finally { setWorking(false); } };
  const handleImages = async () => { if (images) { setImages(false); notify("已隐藏配图"); return; } setWorking(true); try { const response = await fetch("/api/images", { method: "POST", headers: { "Content-Type": "application/json" }, body: JSON.stringify({ prompt: `${topic}，公众号文章封面，现代编辑风，留白构图`, size: "1024x1024" }) }); const data = await response.json(); setArticle({ ...article, imageUrl: data.url || null }); setImages(true); notify(data.demo ? "已生成配图占位（配置图片模型后可生成真实图片）" : "封面与段落图生成完成"); } catch { notify("配图失败，请稍后重试"); } finally { setWorking(false); } };
  const displayContent = humanized ? (article?.humanizedContent || article?.content) : article?.content;
  const handlePublish = async () => { if (!article) return; setWorking(true); try { const response = await fetch("/api/publish", { method: "POST", headers: { "Content-Type": "application/json" }, body: JSON.stringify({ platform: "wechat", title: article.title || topic, content: displayContent, coverUrl: article.imageUrl }) }); const data = await response.json(); if (!response.ok) throw new Error(data.error || "发布失败"); notify(data.message || "已加入发布队列"); } catch (error: any) { notify(error.message || "发布失败，请检查配置"); } finally { setWorking(false); } };
  const currentStep = images ? 3 : humanized ? 2 : generated ? 1 : 0;
  const renderArticle = (content: string) => <>{(content || "").split("\n").filter(Boolean).slice(0, 8).map((line:string, i:number)=>(line.startsWith("##") ? <h3 key={i}>{line.replace(/^##\s*/,"")}</h3> : <p className={line.startsWith("“")?"quote":""} key={i}>{line}</p>))}</>;
  return <div className="page write-page"><div className="page-heading"><div><p className="eyebrow">创作工作台</p><h1>写一篇新文章</h1><p className="hero-sub">把一个想法，变成值得分享的内容。</p></div><div className="autosave"><span className="green-dot"/> 自动保存已开启</div></div><div className="stepper">{steps.map((s:string,i:number)=><div className={i===currentStep ? "step active" : i<currentStep ? "step done" : "step"} key={s}><span>{i<currentStep?<Check size={13}/>:i+1}</span>{s}{i<steps.length-1&&<i/>}</div>)}</div>
    <div className="write-layout"><div className="write-main"><div className="panel"><div className="panel-title"><div><h2>告诉我你想写什么</h2><p>描述越具体，生成的内容越贴近你的想法。</p></div><span className="tip"><Sparkles size={15}/> AI 辅助</span></div><label>文章主题</label><textarea value={topic} onChange={(e:any)=>setTopic(e.target.value)} rows={3}/><div className="label-row"><label>写作风格</label><span>{style === "高流量 / 爆款" ? "推荐" : ""}</span></div><div className="style-grid">{styles.map(([name, length, desc])=><button className={style===name?"style-option selected":"style-option"} key={name} onClick={()=>setStyle(name)}><span className="radio">{style===name&&<i/>}</span><div><b>{name}</b><small>{length} · {desc}</small></div></button>)}</div><div className="option-row"><div className="option-label"><div className="option-icon"><Search size={17}/></div><div><b>先搜索资料再写作</b><small>调用 Firecrawl 获取最新信息，让文章更有依据</small></div></div><button className={searchOn?"toggle on":"toggle"} onClick={()=>setSearchOn(!searchOn)}><i/></button></div><button className="generate-btn" onClick={start} disabled={running}>{running?<><RefreshCw className="spin" size={18}/> 正在生成中...</>:<><Sparkles size={18}/> 开始生成文章 <span>⌘ Enter</span></>}</button></div></div>
      <aside className="write-side"><div className="side-card"><div className="side-card-title"><Sparkles size={16}/> 本次生成会包含</div>{[[<FileText size={16}/> ,"3–5 个备选标题"],[<BookOpen size={16}/>,"完整文章正文"],[<LayoutDashboard size={16}/>,"结构化排版建议"],[<Clock3 size={16}/>,"预计 2–4 分钟"]].map(([icon,text],i)=><div className="include-row" key={i}>{icon}<span>{text}</span><Check size={15}/></div>)}</div><div className="side-card tips-card"><div className="side-card-title"><Bot size={16}/> 写作小贴士</div><p>好的主题通常包含「对象 + 场景 + 结果」。比如：</p><div className="example">“帮我写一篇给产品经理看的，关于 AI 提效的实操指南”</div></div></aside></div>
    {generated && <div className="result-panel"><div className="result-header"><div><span className="pill success">已生成</span><h2>{article?.title || topic}</h2><p>{style} · {(displayContent || "").length.toLocaleString()} 字 · {article?.alternatives?.length || 3} 个备选标题</p></div><button className="ghost-btn" onClick={start} disabled={running}> <RefreshCw size={16}/> 重新生成</button></div><div className="result-actions"><button className={humanized?"action active":"action"} onClick={humanized?()=>{setHumanized(false);notify("已显示原文")}:handleHumanize} disabled={working}><Wand2 size={16}/> {humanized?"查看原文":"AI 去痕处理"}</button><button className={images?"action active":"action"} onClick={handleImages} disabled={working}><ImageIcon size={16}/> {images?"隐藏配图":"生成封面与配图"}</button><button className="publish-btn" onClick={handlePublish} disabled={working}><Send size={16}/> 发布到微信公众号</button></div><div className="preview-tabs"><button className={previewTab==="article"?"active":""} onClick={()=>setPreviewTab("article")}>{humanized?"去痕后文章":"文章预览"}</button><button className={previewTab==="compare"?"active":""} onClick={()=>setPreviewTab("compare")}>对比原文</button><button className={previewTab==="layout"?"active":""} onClick={()=>setPreviewTab("layout")}>排版预览</button></div><div className={previewTab==="compare"?"compare-preview":"article-preview"}><div className="preview-cover">{article?.imageUrl ? <img src={article.imageUrl} alt="文章封面"/> : <div className="preview-gradient"/>}<div><span>CONTENT WORKFLOW</span><b>把时间还给<br/>真正重要的事</b></div></div>{previewTab==="compare" ? <div className="compare-columns"><div><small>原文</small>{renderArticle(article?.content || "")}</div><div><small>去痕后</small>{renderArticle(article?.humanizedContent || article?.content || "")}</div></div> : renderArticle(displayContent || "")}{images&&previewTab!=="compare"&&<div className="inline-image"><ImageIcon size={20}/><span>段落配图 · 已插入</span></div>}</div></div>}
  </div>;
}

function SettingsPage({ notify }: { notify: (s:string)=>void }) { const [tab,setTab]=useState("ai"); return <div className="page settings-page"><div className="page-heading"><div><p className="eyebrow">配置中心</p><h1>让墨稿更懂你的工作流</h1><p className="hero-sub">配置模型与发布平台，所有密钥仅保存在本地。</p></div><button className="save-btn" onClick={()=>notify("配置已保存") }><Check size={16}/> 保存配置</button></div><div className="settings-tabs"><button className={tab==="ai"?"active":""} onClick={()=>setTab("ai")}><Bot size={16}/> AI 服务</button><button className={tab==="platform"?"active":""} onClick={()=>setTab("platform")}><KeyRound size={16}/> 平台密钥</button></div>{tab==="ai"?<div className="settings-grid"><div className="panel config-panel"><div className="panel-title"><div><h2>文本模型</h2><p>用于文章生成、去痕与标题创作。</p></div><span className="connected"><span className="green-dot"/> 已连接</span></div><label>中转站 Base URL</label><div className="input-icon"><Link2 size={16}/><input defaultValue="https://fast.sbbbbbbbbb.xyz/v1"/></div><label>API Key</label><div className="input-icon"><KeyRound size={16}/><input type="password" placeholder="sk-••••••••••••••••••••"/></div><label>模型</label><select defaultValue="gpt-4o"><option value="gpt-4o">gpt-4o · 推荐</option><option>gpt-4.1</option><option>claude-3-5-sonnet</option></select><button className="test-btn" onClick={()=>notify("文本模型连接正常")}>测试连接 <ChevronRight size={15}/></button></div><div className="panel config-panel"><div className="panel-title"><div><h2>图片模型</h2><p>用于封面与正文段落配图。</p></div><span className="connected"><span className="green-dot"/> 已连接</span></div><label>图片接口地址</label><div className="input-icon"><Link2 size={16}/><input defaultValue="https://fast.sbbbbbbbbb.xyz/v1/images/generations"/></div><label>API Key</label><div className="input-icon"><KeyRound size={16}/><input type="password" placeholder="sk-••••••••••••••••••••"/></div><label>模型</label><select defaultValue="gpt-image-2.5-flare"><option value="gpt-image-2.5-flare">gpt-image-2.5-flare</option><option>grok-imagine-image-2.0</option></select><button className="test-btn" onClick={()=>notify("图片模型连接正常")}>测试连接 <ChevronRight size={15}/></button></div><div className="panel config-panel firecrawl"><div className="panel-title"><div><h2><Search size={18}/> Firecrawl 搜索</h2><p>为文章生成提供实时资料。</p></div><span className="connected"><span className="green-dot"/> 已连接</span></div><label>Firecrawl API Key</label><div className="input-icon"><KeyRound size={16}/><input type="password" placeholder="fc-••••••••••••••••••••"/></div><div className="firecrawl-foot"><span><Check size={15}/> 搜索结果自动附加来源</span><button className="test-btn" onClick={()=>notify("Firecrawl 连接正常")}>测试连接 <ChevronRight size={15}/></button></div></div></div>:<Platforms notify={notify}/>}</div> }
function Platforms({notify}:{notify:(s:string)=>void}) {
  const [platform,setPlatform]=useState("wechat");
  const items:any[] = [["wechat","微信公众号",<BookOpen/> ,"已配置"],["xiaohongshu","小红书",<PenLine/>,"未配置"],["zhihu","知乎",<FileText/>,"未配置"],["bilibili","B 站",<Youtube/>,"未配置"]];
  const current:any = items.find((x:any)=>x[0]===platform) || items[0];
  const isWechat = platform === "wechat";
  const fields = isWechat ? [["微信公众号 AppID","wx••••••••••••••••"],["微信公众号 AppSecret","••••••••••••••••••••"],["作者名称","开发阿雷"]] : [[`${current[1]} App Key`,"••••••••••••••••••••"],[`${current[1]} App Secret`,"••••••••••••••••••••"]];
  return <div className="platform-layout"><div className="platform-list">{items.map(([id,name,icon,status])=><button className={platform===id?"platform-item active":"platform-item"} key={id} onClick={()=>setPlatform(id)}>{icon}<span><b>{name}</b><small>{status}</small></span><ChevronRight size={15}/></button>)}</div><div className="panel config-panel platform-form"><div className="panel-title"><div><h2>{current[1]}</h2><p>{isWechat ? "配置后可自动创建草稿并发布。" : `配置后可同步内容到${current[1]}。`}</p></div><span className="connected">{isWechat&&<span className="green-dot"/>}{isWechat?"已配置":"未配置"}</span></div>{fields.map(([label,value]:any)=><div key={label}><label>{label}</label><div className="input-icon"><KeyRound size={16}/><input type={label.includes("Secret")?"password":"text"} defaultValue={value}/></div></div>)}{isWechat&&<div className="option-row publish-toggle"><div className="option-label"><div className="option-icon"><Rocket size={17}/></div><div><b>自动发布</b><small>关闭后仅创建草稿，不会直接发布</small></div></div><button className="toggle" onClick={(e:any)=>e.currentTarget.classList.toggle("on")}><i/></button></div>}<button className="save-wide" onClick={()=>notify(`${current[1]}配置已保存`)}>保存{current[1]}配置</button></div></div>;
}
